# Reduce input lag when leaving insert mode in neovim
set-option -sg escape-time 10

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Enable scrolling
set -g mouse on

# window_activity is last time of activity in current window in unix time
# formatting is done with strftime, see man strftime for more information
set -g status-right "maxrn #{t/f/%%H#:%%M %%Y-%%-m-%%d %%A:window_activity} "
